symbols = [
    'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'XRPUSDT', 'DOTUSDT', 'LINKUSDT', 'XTZUSDT', 
    'ADAUSDT', 'SOLUSDT', 'MATICUSDT', 'AVAXUSDT', 'UNIUSDT', 'TRXUSDT', 'XLMUSDT',
    'VETUSDT', 'AXSUSDT', 'ZILUSDT', 'DOGEUSDT', 'ETCUSDT', 'CHZUSDT', 'NEARUSDT', 
    'BCHUSDT', 'AAVEUSDT', 'DASHUSDT', 'LTCUSDT'
]
